export enum SELECTION {
  NEW_LESSON = "NEW_LESSON",
  LESSON_DETAILS = "LESSON_DETAILS",
  NEW_QUESTION = "NEW_QUESTION",
  EDIT_QUESTION = "EDIT_QUESTION",
  AVAILABLE_EXAMS = "AVAILABLE_EXAMS",
  NEW_EXAM = "NEW_EXAM",
  NEW_RANDOM_EXAM = "NEW_RANDOM_EXAM",
  EXAM_DETAILS = "EXAM_DETAILS",
  ΝΟΝΕ = "ΝΟΝΕ",
}

export enum LESSON_CATEGORIES {
  BASIC_REQUIRED = "BASIC_REQUIRED",
  BASIC_DIR_INF = "BASIC_DIR_INF",
  BASIC_DIR_TEL = "BASIC_DIR_TEL",
  SELECT_DIR_INF = "SELECT_DIR_INF",
  SELECT_DIR_TEL = "SELECT_DIR_TEL",
  SELECT_INF_TEL = "SELECT_INF_TEL",
}
